---
title: "strings_and_factors"
author: "Jesus Luevano"
date: "2023-10-17"
output: html_document
---

#load librarys
```{r}
library(rvest)
library(p8105.datasets)
library(stringr)
library(tidyverse)
```

## Strings and manipulations

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "e")

str_replace(string_vec, "jeff", "Jeff Goldsmith")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think") #all positive, but doesn't look at position
str_detect(string_vec, "^i think") # `^` means start of line
str_detect(string_vec, "i think$") #means something after, only pulls out last string?
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "Pumpkin")
str_detect(string_vec, "[Pp]umpkin") #everything within bracket, can match either or
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9]") #range of numbers, but will match anything
str_detect(string_vec, "^[0-9]") #range of numbers, but only at beginning of line
str_detect(string_vec, "[0-9][a-z]") #range of numbers, and then followed by any lower-case letter
```

## looking at 7s

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") # `.` means ANYTHING
```

## Special characters, `\` before it

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[") # need backslash to show special character, but another to make sure it doesn't take it as one too
str_detect(string_vec, "\\[[0-9]")
```


## Factors

```{r}
vec_sex = factor(c("male", "male", "female", "female")) #automatically made female first in alphabetical
vec_sex

as.numeric(vec_sex) 

vec_sex = fct_relevel(vec_sex, "male") #make male first level
vec_sex 

as.numeric(vec_sex)

```

## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj =
  read_html(nsduh_url) %>%
  html_table() %>% #pull out html tables
  first() %>% #only first
  slice(-1) #remove first row, has notes
```

need to tidy this!

```{r}
marj_df =
  table_marj %>%
  select(-contains("P Value")) %>%
  pivot_longer(
    -State, #don't pivot loner on state
    names_to = "age_year", 
    values_to = "percent"
  ) %>%
  separate(age_year, into = c("age", "year"), "\\(") %>%
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-b]",""),
    percent = as.numeric(percent)
    ) %>%
  filter(!State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West"))

marj_df
```

```{r}
marj_df %>%
  filter(age == "18-25") %>%
  mutate(State = fct_reorder(State, percent)) %>%
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


## NYC Restaurant Inspections

```{r}
data("rest_inspec")

rest_inspec |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(names_from = grade, values_from = n)

```

```{r}
inspection_df = 
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C"), boro !="Missing") %>%
  mutate(boro = str_to_title(boro))
inspection_df
```


Pizza places
```{r}
inspection_df %>%
  filter(str_detect(dba, "Pizza")) %>%
  count(boro)

inspection_df %>%
  filter(str_detect(dba, "PIZZA")) %>%
  count(boro)
```

```{r}
inspection_df %>%
  filter(str_detect(dba, "PIZZA")) %>%
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()

inspection_df %>%
  filter(str_detect(dba, "PIZZA")) %>%
  mutate(boro = fct_infreq(boro)) %>% #factor based on frequency order
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()

inspection_df %>%
  filter(str_detect(dba, "PIZZA")) %>%
  mutate(
    boro = fct_infreq(boro),
    boro = str_replace(boro, "Manhattan","The City") #incorrect order, replace needs to happen first
    ) %>% #factor based on frequency order
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()

inspection_df %>%
  filter(str_detect(dba, "PIZZA")) %>%
  mutate(
    boro = str_replace(boro, "Manhattan","The City"),
    boro = fct_infreq(boro), #Correct order, replace needs to happen first
    ) %>% #factor based on frequency order
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()

##OR try
inspection_df %>%
  filter(str_detect(dba, "PIZZA")) %>%
  mutate(
    boro = fct_infreq(boro),
    boro = fct_recode(boro, "The City" = "Manhattan"), #Correct order, replace needs to happen first
    ) %>% #factor based on frequency order
  ggplot(aes(x = boro, fill = grade)) +
  geom_bar()
```

